### ISSUE TITLE
SPARQL Namespace and config DTD

### ISSUE THREAD

**Issue by kwSeo** [kwSeo/RDF-Object-Mapper#1]
SPARQL에는 네임스페이스라는 개념이 존재한다. URL을 통해 리소스를 식별하기 때문에 리소스의 식별자가 길어질 수 있다. 그렇게 때문에 네임스페이스를 통해 간단히 할 수 있으며, 이를 정의할 수 있는 기능을 필요로한다. 일반적으로 SPARQL에서는 다음과 같이 네임스페이스를 정의한다.

<code>
PREFIX ns: < URL... >
</code>

 매핑을 위한 기본설정파일에 네임스페이스를 함께 정의할 것이다. 아래는 설정 XML파일에서 네임스페이스를 정의하는 구문이다.

<code>
<xmp><namespace name="ns" url="URL..."/></xmp>
</code>

위와 같은 네임스페이스 태그가 설정들과 함께 정의될 것이다.

**Comment by MoonJH** [comment]
namespace 만들었는데 계속 푸시를 하는데 오류가 납니다

**Comment by kwSeo** [comment]
형 마스터 브랜치에다가 커밋하셨는데요....

**Comment by kwSeo** [comment]
그리고 DTD에 오류있다는데요. Validation하면 오류떠요.

**Comment by kwSeo** [comment]
형 여전히 invalid XML이라는데요. 잘못된 부분이 있데요.

**Comment by MoonJH** [comment]
오류 찾고 다시 올리겠습니다.
