### ISSUE TITLE
SPARQL 쿼리가 수행될 URL 엔드포인트 부분 구현

### ISSUE THREAD

**Issue by kwSeo** [kwSeo/RDF-Object-Mapper#11]
- 생성된 SPARQL 퀴리를 URL(또는 웹)을 통해 실행하는 모듈 디자인 및 구현.
- 엔드포인트는 URL을 인자로 받는다.

**Comment by kwSeo** [comment]
쿼리를 실행하기 위한 모듈을 개발하는데 먼저 EndpointProcesser라는 인터페이스를 정의했봤어요. 형이 담당하신 URL을 통한 쿼리를 할때 이 인터페이스가 필요하시면 쓰세요.

**Comment by MoonJH** [comment]
알았어. 확인하고 바로 작업 시작할께 :v:

**Comment by kwSeo** [comment]
EndpointProcesser 구현할 때 제가 작성해둔 EndpointProcesser 인터페이스를 통해 구현해 주세요.
그리고 테스트코드도 포함해주시고 그리고....
이것도 develop 브렌치에서 따로 브렌치 생성해서 작업해주세요.
