### ISSUE TITLE
Config XML파일을 파싱하여 생성되는 ContextConfig 클래스 디자인

### ISSUE THREAD

**Issue by kwSeo** [kwSeo/RDF-Object-Mapper#7]
정의된 Configuration XML파일을 파싱하여 클래스 객체로 사용할 수 있는 설정 클래스 디자인.
ContextConfig 인터페이스를 디자인하며 Configuration을 구현한 클래스 정의와 그 객체를 생성하여 사용할 수 있는 모듈을 정의합니다.
XML파일에 접근하는 방법은 XMLManager 클래스를 사용합니다. XMLManager는 XPath를 사용하는 클래스입니다. XPath 표현식을 사용하여 XML파일에 접근할 수 있습니다. XMLManager 클래스를 사용하는 예제는 test폴더에서 찾아볼 수 있습니다.

**Comment by kwSeo** [comment]
형 ContextConfig......

**Comment by MoonJH** [comment]
ContextConfig 디자인 작성했어. 확인 해주세요 :sob:

**Comment by kwSeo** [comment]
모두 테스트도 된건가요?

**Comment by kwSeo** [comment]
pullrequest할때 테스트 코드도 함께 해주세요.

**Comment by kwSeo** [comment]
형 ContextConfig에서 Namepsaces와 Endpoints와 같이 DTD 상에서 오직 하나만 정의하도록 하는 것들이 List로 반환되고 있어요. 수정 부탁드려요.

**Comment by kwSeo** [comment]
그리고 Namespace 클래스의 멤버필드들이 모두 public으로 선언되어있네요? 따로 이유가 있으신건가요?

**Comment by kwSeo** [comment]
그리고 Endpoint 검색시 이진검색을 하고 있는데 검색대상이되는 리스트가 정렬이 안되어있는거 같은데요.

**Comment by kwSeo** [comment]
테스트를 수행하는 코드가 없어요...

**Comment by kwSeo** [comment]
위 사항들 수정하실때 이미 병합된 브랜치말고 새로운 브랜치 생성해서 작업해 주세요.
제가 지금 병합된 ContextConfig으로 MappingSession 구현하고 있거든요ㅎㅎㅎ

**Comment by kwSeo** [comment]
Endpoint의 Property가 없다고 나옵니다. List<Property>의 length가 0이라고 나와요.
